name: "Release"

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' }}
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.TOKEN }}
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test

  generate-jar:
    if: ${{ github.event_name == 'push' }}
#    needs: build-and-test
    name: Generate Jar
    runs-on: ubuntu-latest
    steps:
      - name: Read Application Config
        run: |
          echo "APP_NAME=$(grep 'info.app.name' ${{ github.workspace }}/src/main/resources/application.yml | awk -F: '{print $2}' | tr -d ' ')" >> $GITHUB_ENV
          echo "APP_VERSION=$(grep 'info.app.version' ${{ github.workspace }}/src/main/resources/application.yml | awk -F: '{print $2}' | tr -d ' ')" >> $GITHUB_ENV
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build PROD with Gradle
        run: ./gradlew clean build -x test -Pvaadin.productionMode
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: build/libs/wydarzeniawokolicy-0.0.1-SNAPSHOT.jar
  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: generate-jar
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.TOKEN }}
      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: artifact
      - name: Deploy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "wydarzeniawokolicy-0.0.1-SNAPSHOT.jar"
          target: www/wydarzeniawokolicy
      - name: run app
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: kill -9 $(pgrep -f 'wydarzeniawokolicy') & screen -d -m -S wydarzeniawokolicy java -jar ./www/wydarzeniawokolicy/wydarzeniawokolicy-0.0.1-SNAPSHOT.jar --server.port=${{ secrets.APP_PORT }}